# [Read the Docs] configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
    builder: html
    configuration: docs/conf.py
    fail_on_warning: true

python:
    version: 3.6
    install:
        - requirements: requirements_docs.txt
